#ifndef __TUNCLIENT_H__
#define __TUNCLIENT_H__  

#define ERR_CODE_LOG 1
#define ERR_CODE_TUNN_CREATE 2
#define ERR_CODE_TUNN_UP 3
#define ERR_CODE_SOCK_CREATE 4
#define ERR_CODE_TUN_IF_CFG 5
#define ERR_CODE_IP 6
#define ERR_CODE_INCORRECT_PREFIX_LEN 7
#define ERR_CODE_STITCH_DP 8
#define ERR_CODE_MISSING_ARG 9
#define ERR_CODE_UNKOWN_OPT 10 
#define ERR_CODE_TUN_FD_CLOSE 11
#define ERR_CODE_FORK 12
#define ERR_CODE_STITCH_DP_SOCKET 13
#endif //__TUNCLIENT_H__  
